"""empty message

Revision ID: 0b4cd9ab1213
Revises: eaf9832552bd
Create Date: 2020-08-24 19:07:42.976906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4cd9ab1213'
down_revision = 'eaf9832552bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NY', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NY', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
